apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-162537903
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sekharrfk/argocd-demo
    targetRevision: staging-deployment
    path: infra/k8s/kustomize/overlays/staging/162537903
  destination:
    server: https://kubernetes.default.svc
    namespace: unomi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true