apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-43081656
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sekharrfk/argocd-demo
    targetRevision: staging-deployment
    path: infra/k8s/kustomize/overlays/staging/43081656
  destination:
    server: https://kubernetes.default.svc
    namespace: unomi
  syncPolicy:
    automated:
      selfHeal: true
      prune: true