apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sekharrfk/argocd-demo
    targetRevision: staging-deployment
    path: infra/k8s/argocd/staging/child-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true